package models;
// Generated 9 dic 2022 8:59:42 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clavesanteriores generated by hbm2java
 */
@Entity
@Table(name = "clavesanteriores", catalog = "bd_neptuno2")
public class Clavesanteriores implements java.io.Serializable {

	private Integer numero;
	private String nombre;
	private String clave;

	public Clavesanteriores() {
	}

	public Clavesanteriores(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "numero", unique = true, nullable = false)
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", length = 30)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

}
