package models;
// Generated 9 dic 2022 8:59:42 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalles generated by hbm2java
 */
@Entity
@Table(name = "detalles", catalog = "bd_neptuno2")
public class Detalles implements java.io.Serializable {

	private DetallesId id;
	private Pedidos pedidos;
	private Productos productos;
	private BigDecimal precioUnidad;
	private Short cantidad;
	private Double descuento;

	public Detalles() {
	}

	public Detalles(DetallesId id, Pedidos pedidos, Productos productos) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
	}

	public Detalles(DetallesId id, Pedidos pedidos, Productos productos, BigDecimal precioUnidad, Short cantidad,
			Double descuento) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
		this.precioUnidad = precioUnidad;
		this.cantidad = cantidad;
		this.descuento = descuento;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "pedidoId", column = @Column(name = "pedido_id", nullable = false)),
			@AttributeOverride(name = "productoId", column = @Column(name = "producto_id", nullable = false)) })
	public DetallesId getId() {
		return this.id;
	}

	public void setId(DetallesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pedido_id", nullable = false, insertable = false, updatable = false)
	public Pedidos getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Pedidos pedidos) {
		this.pedidos = pedidos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto_id", nullable = false, insertable = false, updatable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "precio_unidad", scale = 4)
	public BigDecimal getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(BigDecimal precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	@Column(name = "cantidad")
	public Short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Short cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "descuento", precision = 7)
	public Double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Double descuento) {
		this.descuento = descuento;
	}

}
