package models;
// Generated 9 dic 2022 8:59:42 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Envios generated by hbm2java
 */
@Entity
@Table(name = "envios", catalog = "bd_neptuno2", uniqueConstraints = @UniqueConstraint(columnNames = "empresa"))
public class Envios implements java.io.Serializable {

	private Integer id;
	private String empresa;
	private String telefono;
	private Set pedidoses = new HashSet(0);

	public Envios() {
	}

	public Envios(String empresa) {
		this.empresa = empresa;
	}

	public Envios(String empresa, String telefono, Set pedidoses) {
		this.empresa = empresa;
		this.telefono = telefono;
		this.pedidoses = pedidoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "empresa", unique = true, nullable = false, length = 40)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Column(name = "telefono", length = 24)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "envios")
	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

}
