package models;
// Generated 9 dic 2022 8:59:42 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "bd_neptuno2", uniqueConstraints = @UniqueConstraint(columnNames = "producto"))
public class Productos implements java.io.Serializable {

	private Integer id;
	private Categorias categorias;
	private Proveedores proveedores;
	private String producto;
	private String cantidadPorUnidad;
	private BigDecimal precioUnidad;
	private Short unidadesExistencia;
	private Short unidadesPedido;
	private Integer nivelNuevoPedido;
	private boolean suspendido;
	private String notas;
	private BigDecimal iva;
	private Set detalleses = new HashSet(0);

	public Productos() {
	}

	public Productos(String producto, boolean suspendido, BigDecimal iva) {
		this.producto = producto;
		this.suspendido = suspendido;
		this.iva = iva;
	}

	public Productos(Categorias categorias, Proveedores proveedores, String producto, String cantidadPorUnidad,
			BigDecimal precioUnidad, Short unidadesExistencia, Short unidadesPedido, Integer nivelNuevoPedido,
			boolean suspendido, String notas, BigDecimal iva, Set detalleses) {
		this.categorias = categorias;
		this.proveedores = proveedores;
		this.producto = producto;
		this.cantidadPorUnidad = cantidadPorUnidad;
		this.precioUnidad = precioUnidad;
		this.unidadesExistencia = unidadesExistencia;
		this.unidadesPedido = unidadesPedido;
		this.nivelNuevoPedido = nivelNuevoPedido;
		this.suspendido = suspendido;
		this.notas = notas;
		this.iva = iva;
		this.detalleses = detalleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_id")
	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proveedor_id")
	public Proveedores getProveedores() {
		return this.proveedores;
	}

	public void setProveedores(Proveedores proveedores) {
		this.proveedores = proveedores;
	}

	@Column(name = "producto", unique = true, nullable = false, length = 40)
	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad_por_unidad", length = 20)
	public String getCantidadPorUnidad() {
		return this.cantidadPorUnidad;
	}

	public void setCantidadPorUnidad(String cantidadPorUnidad) {
		this.cantidadPorUnidad = cantidadPorUnidad;
	}

	@Column(name = "precio_unidad", scale = 4)
	public BigDecimal getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(BigDecimal precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	@Column(name = "unidades_existencia")
	public Short getUnidadesExistencia() {
		return this.unidadesExistencia;
	}

	public void setUnidadesExistencia(Short unidadesExistencia) {
		this.unidadesExistencia = unidadesExistencia;
	}

	@Column(name = "unidades_pedido")
	public Short getUnidadesPedido() {
		return this.unidadesPedido;
	}

	public void setUnidadesPedido(Short unidadesPedido) {
		this.unidadesPedido = unidadesPedido;
	}

	@Column(name = "nivel_nuevo_pedido")
	public Integer getNivelNuevoPedido() {
		return this.nivelNuevoPedido;
	}

	public void setNivelNuevoPedido(Integer nivelNuevoPedido) {
		this.nivelNuevoPedido = nivelNuevoPedido;
	}

	@Column(name = "suspendido", nullable = false)
	public boolean isSuspendido() {
		return this.suspendido;
	}

	public void setSuspendido(boolean suspendido) {
		this.suspendido = suspendido;
	}

	@Column(name = "notas", length = 65535)
	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	@Column(name = "iva", nullable = false, precision = 14)
	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set getDetalleses() {
		return this.detalleses;
	}

	public void setDetalleses(Set detalleses) {
		this.detalleses = detalleses;
	}

}
