package models;
// Generated 9 dic 2022 8:59:42 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TotalesMensualesId generated by hbm2java
 */
@Embeddable
public class TotalesMensualesId implements java.io.Serializable {

	private Integer año;
	private Integer mes;
	private Date fecha;
	private BigInteger cargo;
	private Double importe;
	private Double total;
	private long numPedidos;

	public TotalesMensualesId() {
	}

	public TotalesMensualesId(long numPedidos) {
		this.numPedidos = numPedidos;
	}

	public TotalesMensualesId(Integer año, Integer mes, Date fecha, BigInteger cargo, Double importe, Double total,
			long numPedidos) {
		this.año = año;
		this.mes = mes;
		this.fecha = fecha;
		this.cargo = cargo;
		this.importe = importe;
		this.total = total;
		this.numPedidos = numPedidos;
	}

	@Column(name = "año")
	public Integer getAño() {
		return this.año;
	}

	public void setAño(Integer año) {
		this.año = año;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "cargo", precision = 38, scale = 0)
	public BigInteger getCargo() {
		return this.cargo;
	}

	public void setCargo(BigInteger cargo) {
		this.cargo = cargo;
	}

	@Column(name = "importe", precision = 22, scale = 0)
	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "num_pedidos", nullable = false)
	public long getNumPedidos() {
		return this.numPedidos;
	}

	public void setNumPedidos(long numPedidos) {
		this.numPedidos = numPedidos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TotalesMensualesId))
			return false;
		TotalesMensualesId castOther = (TotalesMensualesId) other;

		return ((this.getAño() == castOther.getAño())
				|| (this.getAño() != null && castOther.getAño() != null && this.getAño().equals(castOther.getAño())))
				&& ((this.getMes() == castOther.getMes()) || (this.getMes() != null && castOther.getMes() != null
						&& this.getMes().equals(castOther.getMes())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getCargo() == castOther.getCargo()) || (this.getCargo() != null
						&& castOther.getCargo() != null && this.getCargo().equals(castOther.getCargo())))
				&& ((this.getImporte() == castOther.getImporte()) || (this.getImporte() != null
						&& castOther.getImporte() != null && this.getImporte().equals(castOther.getImporte())))
				&& ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null
						&& castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())))
				&& (this.getNumPedidos() == castOther.getNumPedidos());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAño() == null ? 0 : this.getAño().hashCode());
		result = 37 * result + (getMes() == null ? 0 : this.getMes().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getCargo() == null ? 0 : this.getCargo().hashCode());
		result = 37 * result + (getImporte() == null ? 0 : this.getImporte().hashCode());
		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		result = 37 * result + (int) this.getNumPedidos();
		return result;
	}

}
