package models;
// Generated 9 dic 2022 8:59:42 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TotalesMensuales generated by hbm2java
 */
@Entity
@Table(name = "totales_mensuales", catalog = "bd_neptuno2")
public class TotalesMensuales implements java.io.Serializable {

	private TotalesMensualesId id;

	public TotalesMensuales() {
	}

	public TotalesMensuales(TotalesMensualesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "a�o", column = @Column(name = "a�o")),
			@AttributeOverride(name = "mes", column = @Column(name = "mes")),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 10)),
			@AttributeOverride(name = "cargo", column = @Column(name = "cargo", precision = 38, scale = 0)),
			@AttributeOverride(name = "importe", column = @Column(name = "importe", precision = 22, scale = 0)),
			@AttributeOverride(name = "total", column = @Column(name = "total", precision = 22, scale = 0)),
			@AttributeOverride(name = "numPedidos", column = @Column(name = "num_pedidos", nullable = false)) })
	public TotalesMensualesId getId() {
		return this.id;
	}

	public void setId(TotalesMensualesId id) {
		this.id = id;
	}

}
