package models;
// Generated 9 dic 2022 8:59:42 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "bd_neptuno2")
public class Usuarios implements java.io.Serializable {

	private String nombre;
	private String clave;

	public Usuarios() {
	}

	public Usuarios(String nombre) {
		this.nombre = nombre;
	}

	public Usuarios(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	@Id

	@Column(name = "nombre", unique = true, nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", length = 30)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

}
