package models;
// Generated 9 dic 2022 8:59:42 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VNueva generated by hbm2java
 */
@Entity
@Table(name = "v_nueva", catalog = "bd_neptuno2")
public class VNueva implements java.io.Serializable {

	private VNuevaId id;

	public VNueva() {
	}

	public VNueva(VNuevaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "producto", column = @Column(name = "producto", nullable = false, length = 40)),
			@AttributeOverride(name = "proveedorId", column = @Column(name = "proveedor_id")),
			@AttributeOverride(name = "categoriaId", column = @Column(name = "categoria_id")),
			@AttributeOverride(name = "cantidadPorUnidad", column = @Column(name = "cantidad_por_unidad", length = 20)) })
	public VNuevaId getId() {
		return this.id;
	}

	public void setId(VNuevaId id) {
		this.id = id;
	}

}
